"""The public development pack.

Miners get a pack of complete instances — manuals, logs, a SQLite copy of the
maintenance database, the diagnostic cases, inventory, policy, *and* the ground
truth — plus the same scoring code the engine runs. They can therefore reproduce
the entire evaluation offline, which is what makes private composition search
possible at all.

The hidden pack is generated by exactly the same code from a different seed
range and never leaves the engine. Publishing the generator rather than the data
is the point: a miner can study the distribution as long as it likes without
ever seeing the instances it will be scored on.
"""

from __future__ import annotations

import json
import logging
import random
import sqlite3
from dataclasses import asdict, is_dataclass
from pathlib import Path
from typing import Any

from capability_subnet.common import constants as C
from capability_subnet.common.hashing import canonical_json_str, sha256_tree
from capability_subnet.workflows.industrial_maintenance_de_v1.generator import (
    generate_instance,
    sample_seeds,
)
from capability_subnet.workflows.industrial_maintenance_de_v1.instance import WorkflowInstance

log = logging.getLogger(__name__)

#: The published seed for the public pack. Anyone can regenerate the pack from
#: this number and verify it byte for byte.
PUBLIC_PACK_SEED = 20260701

#: Seed for the public out-of-distribution subset, so miners can measure their
#: own robustness before submitting.
PUBLIC_OOD_SEED = 20260702


def _serialise(value: Any) -> Any:
    if is_dataclass(value) and not isinstance(value, type):
        return {key: _serialise(item) for key, item in asdict(value).items()}
    if isinstance(value, dict):
        return {key: _serialise(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_serialise(item) for item in value]
    return value


def instance_to_dict(instance: WorkflowInstance, *, include_truth: bool) -> dict[str, Any]:
    """Serialise an instance.

    ``include_truth`` is the single switch that separates the public pack from
    the hidden one. There is deliberately no way to serialise "most" of the
    truth: it is all or nothing, so a partial leak cannot happen by accident.
    """
    payload = _serialise(instance)
    if not include_truth:
        payload.pop("truth", None)
        payload["diagnostic"].pop("hidden_cases", None)
        payload["database"].pop("rows", None)
    return payload


def write_sqlite(instance: WorkflowInstance, path: Path) -> None:
    """Materialise an instance's maintenance database as SQLite.

    The engine runs the hidden snapshot on PostgreSQL; the DDL is restricted to
    types that behave identically on both, so a query a miner develops against
    this file works unchanged against the hidden snapshot.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        path.unlink()

    connection = sqlite3.connect(path)
    try:
        for statement in instance.database.ddl:
            connection.execute(statement)
        for table, rows in instance.database.rows.items():
            if not rows:
                continue
            placeholders = ", ".join("?" for _ in instance.database.columns[table])
            connection.executemany(
                f"INSERT INTO {table} VALUES ({placeholders})", [tuple(row) for row in rows]
            )
        connection.commit()
    finally:
        connection.close()


def generate_pack(
    output_dir: str | Path,
    *,
    count: int = C.PUBLIC_PACK_INSTANCES,
    ood_count: int = 30,
    seed: int = PUBLIC_PACK_SEED,
    ood_seed: int = PUBLIC_OOD_SEED,
    include_truth: bool = True,
    write_databases: bool = True,
) -> dict[str, Any]:
    """Generate and write a pack.

    Returns:
        A manifest describing what was written, including a tree digest so a
        miner can confirm their copy matches the published one.
    """
    root = Path(output_dir)
    instances_dir = root / "instances"
    databases_dir = root / "databases"
    instances_dir.mkdir(parents=True, exist_ok=True)

    written: list[dict[str, Any]] = []

    for split, split_seed, split_count in (
        ("public", seed, count),
        ("ood", ood_seed, ood_count),
    ):
        if split_count <= 0:
            continue
        rng = random.Random(split_seed)
        for instance_seed in sample_seeds(rng, split_count):
            instance = generate_instance(instance_seed, split=split)
            document = instance_to_dict(instance, include_truth=include_truth)
            target = instances_dir / f"{instance.instance_id}.json"
            target.write_text(canonical_json_str(document), encoding="utf-8")

            if write_databases:
                write_sqlite(instance, databases_dir / f"{instance.instance_id}.sqlite")

            written.append(
                {
                    "instance_id": instance.instance_id,
                    "seed": instance.seed,
                    "split": instance.split,
                    "machine_model": instance.machine_model_de,
                    "sensor": instance.sensor_key,
                    "ood_mutations": list(instance.ood_mutations),
                }
            )

    manifest = {
        "workflow_id": C.DEFAULT_WORKFLOW_ID,
        "pack_seed": seed,
        "ood_pack_seed": ood_seed,
        "instance_count": len([item for item in written if item["split"] == "public"]),
        "ood_count": len([item for item in written if item["split"] == "ood"]),
        "includes_ground_truth": include_truth,
        "instances": written,
    }

    (root / "manifest.json").write_text(canonical_json_str(manifest), encoding="utf-8")

    manifest["tree_sha256"] = sha256_tree(instances_dir, suffixes=(".json",))
    (root / "manifest.json").write_text(canonical_json_str(manifest), encoding="utf-8")

    log.info(
        "wrote %d instances to %s (tree %s)",
        len(written),
        root,
        manifest["tree_sha256"][:19],
    )
    return manifest


def load_pack(directory: str | Path) -> list[dict[str, Any]]:
    """Read a previously generated pack back as raw documents."""
    instances_dir = Path(directory) / "instances"
    return [
        json.loads(path.read_text(encoding="utf-8"))
        for path in sorted(instances_dir.glob("*.json"))
    ]
